// generated by cmd/gen; DO NOT EDIT

package service

const (
	TypeAccessoryInformation          = "3E"
	TypeAirPurifier                   = "BB"
	TypeAirQualitySensor              = "8D"
	TypeAudioStreamManagement         = "127"
	TypeBatteryService                = "96"
	TypeCameraRecordingManagement     = "204"
	TypeCameraRTPStreamManagement     = "110"
	TypeCarbonDioxideSensor           = "97"
	TypeCarbonMonoxideSensor          = "7F"
	TypeContactSensor                 = "80"
	TypeDataStreamTransportManagement = "129"
	TypeDoor                          = "81"
	TypeDoorbell                      = "121"
	TypeFan                           = "40"
	TypeFanv2                         = "B7"
	TypeFaucet                        = "D7"
	TypeFilterMaintenance             = "BA"
	TypeGarageDoorOpener              = "41"
	TypeHAPProtocolInformation        = "A2"
	TypeHeaterCooler                  = "BC"
	TypeHumidifierDehumidifier        = "BD"
	TypeHumiditySensor                = "82"
	TypeInputSource                   = "D9"
	TypeIrrigationSystem              = "CF"
	TypeLeakSensor                    = "83"
	TypeLightbulb                     = "43"
	TypeLightSensor                   = "84"
	TypeLockManagement                = "44"
	TypeLockMechanism                 = "45"
	TypeMicrophone                    = "112"
	TypeMotionSensor                  = "85"
	TypeOccupancySensor               = "86"
	TypeOutlet                        = "47"
	TypeSecuritySystem                = "7E"
	TypeServiceLabel                  = "CC"
	TypeSiri                          = "133"
	TypeSlat                          = "B9"
	TypeSmokeSensor                   = "87"
	TypeSpeaker                       = "113"
	TypeStatelessProgrammableSwitch   = "89"
	TypeSwitch                        = "49"
	TypeTargetControl                 = "125"
	TypeTargetControlManagement       = "122"
	TypeTelevision                    = "D8"
	TypeTemperatureSensor             = "8A"
	TypeThermostat                    = "4A"
	TypeValve                         = "D0"
	TypeWindow                        = "8B"
	TypeWindowCovering                = "8C"
)

var typeMetadatas = []*TypeMetadata{
	{TypeAccessoryInformation, "AccessoryInformation"},
	{TypeAirPurifier, "AirPurifier"},
	{TypeAirQualitySensor, "AirQualitySensor"},
	{TypeAudioStreamManagement, "AudioStreamManagement"},
	{TypeBatteryService, "BatteryService"},
	{TypeCameraRecordingManagement, "CameraRecordingManagement"},
	{TypeCameraRTPStreamManagement, "CameraRTPStreamManagement"},
	{TypeCarbonDioxideSensor, "CarbonDioxideSensor"},
	{TypeCarbonMonoxideSensor, "CarbonMonoxideSensor"},
	{TypeContactSensor, "ContactSensor"},
	{TypeDataStreamTransportManagement, "DataStreamTransportManagement"},
	{TypeDoor, "Door"},
	{TypeDoorbell, "Doorbell"},
	{TypeFan, "Fan"},
	{TypeFanv2, "Fanv2"},
	{TypeFaucet, "Faucet"},
	{TypeFilterMaintenance, "FilterMaintenance"},
	{TypeGarageDoorOpener, "GarageDoorOpener"},
	{TypeHAPProtocolInformation, "HAPProtocolInformation"},
	{TypeHeaterCooler, "HeaterCooler"},
	{TypeHumidifierDehumidifier, "HumidifierDehumidifier"},
	{TypeHumiditySensor, "HumiditySensor"},
	{TypeInputSource, "InputSource"},
	{TypeIrrigationSystem, "IrrigationSystem"},
	{TypeLeakSensor, "LeakSensor"},
	{TypeLightbulb, "Lightbulb"},
	{TypeLightSensor, "LightSensor"},
	{TypeLockManagement, "LockManagement"},
	{TypeLockMechanism, "LockMechanism"},
	{TypeMicrophone, "Microphone"},
	{TypeMotionSensor, "MotionSensor"},
	{TypeOccupancySensor, "OccupancySensor"},
	{TypeOutlet, "Outlet"},
	{TypeSecuritySystem, "SecuritySystem"},
	{TypeServiceLabel, "ServiceLabel"},
	{TypeSiri, "Siri"},
	{TypeSlat, "Slat"},
	{TypeSmokeSensor, "SmokeSensor"},
	{TypeSpeaker, "Speaker"},
	{TypeStatelessProgrammableSwitch, "StatelessProgrammableSwitch"},
	{TypeSwitch, "Switch"},
	{TypeTargetControl, "TargetControl"},
	{TypeTargetControlManagement, "TargetControlManagement"},
	{TypeTelevision, "Television"},
	{TypeTemperatureSensor, "TemperatureSensor"},
	{TypeThermostat, "Thermostat"},
	{TypeValve, "Valve"},
	{TypeWindow, "Window"},
	{TypeWindowCovering, "WindowCovering"},
}
